var no  : number = 11;
console.log("Value of no is : " + no);
console.log(typeof(no));
var str : string = "Angular";
console.log("Value of str is : " + str);
console.log(typeof(str));
var value ;
console.log("Value of str is : " + value);
console.log(typeof(value));
var batches : string[] = ["PPA","PML","LB",];
console.log("First element is : "+batches[0]);
console.log("Second  element is : "+batches[1]);
console.log("Third element is : "+batches[2]);
batches[3] = "LSP";
console.log("Fourth element is : "+batches[3]);
batches[1] = "AngularMean";
console.log("Updated Second  element is : "+batches[1]);
console.log("All batches are : ",batches);
console.log("Lenght of array is : "+ batches.length)
console.log(typeof(batches));
var arr: any[] = ["PPA"];
arr[1] = 11;
console.log(arr);
console.log("Hello World!");
const brr : number[] = [10,20,30,40];
console.log(brr);
console.log(typeof(brr));
console.log(brr[1]);
brr[4] = 50;
console.log(brr);
brr[1] = 21;
console.log(brr);